spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    connection-timeout: 60s
    virtual-host=: "/"
    listener:
      direct:
        acknowledge-mode: none

  # Mqtt配置
  mqtt:
    serverURIs: tcp://47.97.114.254:18083
    username: admin
    password: password
    client:
      id: ${random.value}
    topic: topic_default